---
fontsize: 11pt
documentclass: article
bibliography: Endnote_lib.bib
csl: reference-style.csl
output:
  rmarkdown::pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: [preamble-latex.tex, preamble-latex2.tex]
---

```{r, include=FALSE}
# set wd
setwd('..')

# load .rda file
try(session::restore.session('results/results.rda'))

# set options
options(error=NULL)

```

## Figures

```{r, echo=FALSE, message=FALSE, fig.width=6, fig.height=4.5, fig.cap='The relationship between surrogates and genetic variation secured in prioritizations. Panel (a) shows the relationship between environmental surrogate targets used to generate a prioritization and the proportion of adaptive genetic variation it secures. Similarly, panel (b) shows that for geographic surrogate targets and neutral genetic variation. Box-plots show inter-specific variation in the proportion of genetic variation secured using different surrogate-based targets. Letters indicate significant differences ($P < 0.05$).'}
# prepare data
env.correlation.DF$Surrogate.target <- factor(env.correlation.DF$Surrogate.target)
env.correlation.DF2 <- env.correlation.DF %>%
	group_by(Surrogate.target, Method, Type) %>% 
	summarize(genetic.held=max(genetic.held, na.rm=TRUE)+0.1) %>%
	ungroup() %>% mutate(Combination=as.character(paste0(Surrogate.target,'.',Method,'.',Type))) %>% 
	left_join(
		data.frame(
			letter=unname(toupper(cld(posthoc.correlation.GLHT)$mcletters$Letters)),
			Combination=as.character(names(toupper(cld(posthoc.correlation.GLHT)$mcletters$Letters))),
			stringsAsFactors=FALSE
		),
		by='Combination'
	) %>% data.frame()

geo.correlation.DF$Surrogate.target <- factor(geo.correlation.DF$Surrogate.target)
geo.correlation.DF2 <- geo.correlation.DF %>%
	group_by(Surrogate.target, Method, Type) %>% 
	summarize(genetic.held=max(genetic.held, na.rm=TRUE)+0.1) %>%
	ungroup() %>% mutate(Combination=as.character(paste0(Surrogate.target,'.',Method,'.',Type))) %>% 
	left_join(
		data.frame(
			letter=unname(toupper(cld(posthoc.correlation.GLHT)$mcletters$Letters)),
			Combination=as.character(names(toupper(cld(posthoc.correlation.GLHT)$mcletters$Letters))),
			stringsAsFactors=FALSE
		),
		by='Combination'
	) %>% data.frame()
	
# make figure
p1 <- ggplot(aes(x=Surrogate.target,y=genetic.held, color=Method),
		data=env.correlation.DF) +
	geom_boxplot(position=position_dodge(0.9)) +
	xlab('Environmental surrogate target (%)') + 
	ylab('Adaptive genetic\nvariation secured (%)') +
	geom_text(aes(x=0.55, y=1.125, label='(a)'), color='black', size=5) +
	theme_classic() +
	theme(legend.position=c(0.9,0.4)) +
	scale_color_manual(name='Prioritization', values=c('Optimal'='black', 'Random'='grey50')) +
	geom_text(aes(x=Surrogate.target, y=genetic.held, color=Method, label=letter),
		data=env.correlation.DF2, position=position_dodge(0.9))

p2 <- ggplot(aes(x=Surrogate.target,y=genetic.held, color=Method),
			data=geo.correlation.DF) +
	geom_boxplot(position=position_dodge(0.9)) +
	xlab('Geographic surrogate target (%)') + 
	ylab('Neutral genetic\nvariation secured (%)') +
	geom_text(aes(x=0.55, y=1.125, label='(b)'), color='black', size=5) +
	theme_classic() +
	theme(legend.position='none') +
	scale_color_manual(name='Prioritization', values=c('Optimal'='black', 'Random'='grey50')) +
	geom_text(aes(x=Surrogate.target, y=genetic.held, color=Method, label=letter),
		data=geo.correlation.DF2, position=position_dodge(0.9))

# render figure
grid.arrange(p1,p2,nrow=2)

```


```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=5, fig.height=5, fig.cap='Planning unit selection frequencies. The top row of panels (a, b, c) show single-species prioritizations generated assuming equal costs. The middle row of panels (d, e, f) show multi-species prioritizations generated assuming equal costs. The bottom row of panels (g, h, i) show multi-species generated using opportunity costs. The left column of panels (a, d, g) show prioritizations generated using only amount-based targets. The middle column of panels (b, e, h) show prioritizations generated using amount- and surrogate-based targets. The right column of panels (c, f, i) show prioritizations generated using amount- and genetic-based targets.'}
# download basemap
data(countriesHigh)
countries.FPLY <- countriesHigh[
	countriesHigh$ADMIN %in% c(
		'Italy', 'Switzerland', 'France', 'Austria',
		'Germany', 'Slovenia', 'Croatia', 'Hungary',
		'Monaco', 'Germany', 'Slovakia', 'Czech Republic'
	)
,] %>% spFortify
# prepare data for plotting
grid.FPLY <- grid.PLY
for (i in seq_along(single.spp.prioritisations[[1]]))
	grid.FPLY@data[[paste0('Single-species (equal costs).', c('Amount', 'Surrogate', 'Genetic')[i])]] <- rowMeans(sapply(single.spp.prioritisations, function(x){colMeans(x[[i]]@results@selections)}))
for (i in seq_along(multi.spp.prioritisations))
	grid.FPLY@data[[paste0('Multi-species (equal costs).', c('Amount', 'Surrogate', 'Genetic')[i])]] <- colMeans(multi.spp.prioritisations[[i]]@results@selections)
for (i in seq_along(multi.spp.prioritisations.with.cost))
	grid.FPLY@data[[paste0('Multi-species (opportunity costs).', c('Amount', 'Surrogate', 'Genetic')[i])]] <- colMeans(multi.spp.prioritisations.with.cost[[i]]@results@selections)
grid.FPLY <- spFortify(grid.FPLY)
grid.FPLY <- grid.FPLY %>% gather(
		Combination,
		`Selection.Frequency`,
		`Single-species (equal costs).Amount`:`Multi-species (opportunity costs).Genetic`
	) %>% mutate(
		Context=sapply(strsplit(as.character(Combination), '.', fixed=TRUE), `[[`, 1),
		Prioritization=sapply(strsplit(as.character(Combination), '.', fixed=TRUE), `[[`, 2)
	) %>% mutate(
		Prioritization=factor(Prioritization, levels=c('Amount', 'Surrogate', 'Genetic')),
		Context=factor(
			gsub(' (', '\n(', Context, fixed=TRUE),
			levels=c("Single-species\n(equal costs)", "Multi-species\n(equal costs)", 
			"Multi-species\n(opportunity costs)"))
	)
panel.DF <- grid.FPLY %>% select(Context, Prioritization, long, lat) %>% 
	mutate(
		lat=min(lat)+(diff(range(lat))*0.98),
		long=min(long)+(diff(range(long))*0.02)
	) %>%
	group_by(Context,Prioritization) %>% filter(c(TRUE, rep(FALSE, length(Context)-1))) %>%
	mutate(
		panel.letter=paste0('(',letters[(as.integer(Context)-1)*3 + as.integer(Prioritization)],')'),
		panel.letter=c(as.character(panel.letter[1]), rep(NA_character_, length(Context)-1))
	)
# make maps
ggplot() +
	geom_polygon(data=countries.FPLY, aes(x=long, y=lat, group=group),
		fill='grey85', color='grey70') +
	geom_polygon(data=grid.FPLY, aes_string(x='long', y='lat', 
		group='group', fill='Selection.Frequency'),
		alpha=0.8, color='grey10') +
	geom_text(aes_string(x='long',y='lat', label='panel.letter'), data=panel.DF) +
	theme_classic() +
	theme(axis.ticks=element_blank(), axis.text=element_blank(),
		plot.margin=unit(c(0,0,0,0),'cm'), axis.line=element_blank(),
		strip.background = element_rect(fill='grey20'),
		strip.text = element_text(color='white'),
		legend.position='bottom', legend.key.width=unit(1.8, 'cm'),
		legend.title=element_text(vjust=-5),
		legend.margin=unit(c(0.1), 'cm'),
		axis.title=element_blank()) +
	coord_cartesian(
		xlim=buffered.range(grid.FPLY$long, 0),
		ylim=buffered.range(grid.FPLY$lat, 0)
	) +
	facet_grid(Context ~ Prioritization) +
	scale_fill_gradientn(name='Selection Frequency (%)',
		colors=brewer.pal(9, 'PuBu'),
		guide=guide_colorbar(title.position='bottom', title.hjust=0.5,
			ticks=element_line(color='black'), border=element_line(color='black'))
	)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=5, fig.height=5, fig.cap='The effectiveness of prioritizations at securing genetic variation. The top row of panels (a--b) show the performance of single-species prioritizations generated assuming equal costs among planning costs. The middle row of panels (c--d) show the performance of multi-species prioritizations generated assuming equal costs among planning units. The bottom row of panels (e--f) show the performance of multi-species prioritizations generated using opportunity costs. The left column of panels (a, c, d) and the right column of panels (b, d, f) show the proportion of adaptive and neutral genetic variation secured (respectively). Box plots show the effectiveness of prioritizations generated using amount-based targets, amount-based and surrogate-based targets, and amount-based and genetic-based targets for each species. Letters denote significant differences ($P < 0.05$).'}
# prepare data for plotting
results.SDF <- results.SDF %>% mutate(
		Prioritisation=factor(as.character(Prioritisation), levels=c('Amount','Surrogate','Genetic')),
		Context=factor(as.character(Context), levels=c("single-species (equal costs)", "multi-species (equal costs)", "multi-species (opportunity costs)")),
		Metric=factor(as.character(Metric), c("Adaptive variation", "Neutral variation"))
	)
results.PDF <- results.SDF %>% group_by(
		Prioritisation, Context, Metric
	) %>% mutate(
		letter.height=max(value, na.rm=TRUE)+0.1,
		Combination=paste0(Prioritisation,'.',Metric,'.',Context)
	) %>% filter(
		c(TRUE, rep(FALSE, length(Context)-1))
	) %>% data.frame() %>% group_by(Context, Metric) %>% mutate(
		panel.letter=paste0('(',letters[as.integer(Context) + (as.integer(Metric)-1)],')'),
		panel.letter=c(as.character(panel.letter[1]), rep(NA_character_, length(Context)-1))
	) %>% data.frame() %>% left_join(
		data.frame(
			letter=unname(toupper(cld(posthoc.scenario.GLHT)$mcletters$Letters)),
			Combination=as.character(names(toupper(cld(posthoc.scenario.GLHT)$mcletters$Letters)))
		) %>% mutate(Combination=as.character(Combination)),
		by='Combination'
	) %>% data.frame()
results.SDF <- results.SDF %>% mutate(
	Context=sapply(as.character(Context), function(x) {paste0(toupper(substr(x, 1, 1)), substr(x, 2, nchar(x)))}),
	Context=factor(
		gsub(' (', '\n(', Context, fixed=TRUE),
		levels=c("Single-species\n(equal costs)",
		"Multi-species\n(equal costs)", 
		"Multi-species\n(opportunity costs)"))
	)
results.PDF <- results.PDF %>% mutate(
	Context=sapply(as.character(Context), function(x) {paste0(toupper(substr(x, 1, 1)), substr(x, 2, nchar(x)))}),
	Context=factor(
		gsub(' (', '\n(', Context, fixed=TRUE),
		levels=c("Single-species\n(equal costs)",
		"Multi-species\n(equal costs)", 
		"Multi-species\n(opportunity costs)"))
	)

# make plot
suppressWarnings({
	ggplot(aes(x=Prioritisation,y=value),
		data=results.SDF) +
		geom_boxplot(position=position_dodge(0.9)) +
		geom_text(aes(x=Prioritisation, y=letter.height, label=letter),
			data=results.PDF, position=position_dodge(0.9)) +
		geom_text(aes(x=0.7, y=1.05, label=panel.letter),
			data=results.PDF) +
		scale_fill_manual(name='Prioritisation',
			values=c('grey80','grey50','grey20')) +
		ylab('Genetic variation secured (%)') +
		xlab('') +
		scale_y_continuous(breaks=c(0,0.25,0.5,0.75,1), limits=c(NA, 1.2)) +
		theme_classic() +
		theme(strip.background = element_rect(fill='grey20'),
			strip.text = element_text(color='white'),
			panel.border = element_rect(color='black', fill=NA),
			axis.text.x=element_text(angle=45, hjust=1, vjust=1)) +
		facet_grid(Context ~ Metric)
})
```

