---
fontsize: 11pt
documentclass: article
bibliography: Endnote_lib.bib
csl: reference-style.csl
output:
  rmarkdown::pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: [preamble-latex.tex, preamble-latex3.tex]
---
## Supporting Information
All data and code is stored in an online repository (\url{www.github.com/paleo13/genetic.surrogates}) to replicate analyses in this study. See the \textit{README} file for instructions.


```{r, include=FALSE}
# set wd
setwd('..')

# load .rda file
try(session::restore.session('results/results.rda'))

# set options
options(error=NULL)

# download basemap
data(countriesHigh)
countries.FPLY <- countriesHigh[
	countriesHigh$ADMIN %in% c(
		'Italy', 'Switzerland', 'France', 'Austria',
		'Germany', 'Slovenia', 'Croatia', 'Hungary',
		'Monaco', 'Germany', 'Slovakia', 'Czech Republic'
	)
,] %>% spFortify
grid.FPLY <- spFortify(grid.PLY)

# define ggplot2 color wheel function
gg_color_hue <- function(n) {
	hues <- seq(15, 375, length=n+1)
	hcl(h=hues, l=65, c=100)[1:n]
}
```

```{r, echo=FALSE, fig.width=9.5, fig.height=10, out.width='7.5in', out.height='8.5in', fig.cap='Species distributions. Squares represent planning units. For a given species, planning units that were found to be inhabited are denoted with bright blue.'}
## plot map of species distributions
# fortify data
spp.grid.FPLY <- ldply(unique(spp.samples.DF$species), function(x) {
		z <- grid.FPLY[,c('long', 'lat', 'group', x),drop=FALSE]
		names(z)[4] <- 'presence'
		z$species <- gsub('\\_', ' ', x)
		return(z)
	}
)
# plot species data
ggplot() +
	geom_polygon(data=countries.FPLY, aes(x=long, y=lat, group=group),
		fill='grey85', color='grey70') +
	geom_polygon(data=spp.grid.FPLY, aes(x=long, y=lat, 
		group=group, fill=presence), alpha=0.8, color='grey10') +
	theme_classic() +
	guides(fill=guide_legend(title='Presence')) +
	theme(
		axis.ticks=element_blank(), axis.text=element_blank(), axis.line=element_blank(), plot.margin = unit(c(0, 0, 0, 0), "lines"),
		strip.background = element_rect(fill='grey20'),
		strip.text = element_text(color='white', face='italic'),
		axis.title=element_blank()
	) +
	coord_cartesian(
		xlim=buffered.range(grid.FPLY$long, 0),
		ylim=buffered.range(grid.FPLY$lat, 0)
	) +
	facet_wrap(~ species, ncol=4)
```

```{r, echo=FALSE, fig.width=4, fig.height=2.5, fig.cap="Species richness. Squares denote planning units. Planning units with a brighter color are inhabited by more species."}
# calculate species richness
grid.PLY$Species_richness <- grid.PLY@data %>%
	select(5:(4+n_distinct(spp.samples.DF$species))) %>% as.matrix() %>% rowSums()
# plot species richness
ggplot() +
	geom_polygon(data=countries.FPLY, aes(x=long, y=lat, group=group),
		fill='grey85', color='grey70') +
	geom_polygon(data=spFortify(grid.PLY), aes(x=long, y=lat, 
		group=group, fill=Species_richness), color='grey10') +
	scale_fill_gradientn(name='Richness (#)',
		colors=brewer.pal(9,'PuBu'),
		guide=guide_colorbar(ticks=element_line(color='black'), border=element_line(color='black'))
	) +
	theme_classic() +
	theme(
		axis.ticks=element_blank(), axis.text=element_blank(), axis.line=element_blank(), plot.margin = unit(c(0, 0, 0, 0), "lines"), axis.title=element_blank(),
		panel.border=element_rect(color='black', fill=NA, size=1)
	) +
	coord_cartesian(
		xlim=buffered.range(grid.FPLY$long, 0),
		ylim=buffered.range(grid.FPLY$lat, 0)
	)
```

```{r, echo=FALSE, fig.width=4, fig.height=2.5, fig.cap="Opportunity cost. Squares denote planning units. The color of each planning unit represents its opportunity cost (computed as total population density)"}
# plot opportunity costs
ggplot() +
	geom_polygon(data=countries.FPLY, aes(x=long, y=lat, group=group),
		fill='grey85', color='grey70') +
	geom_polygon(data=spFortify(grid.PLY), aes(x=long, y=lat, 
		group=group, fill=pop.density), color='grey10') +
	scale_fill_gradientn(name='Cost',
		colors=brewer.pal(9, 'PuBu'),
		guide=guide_colorbar(ticks=element_line(color='black'), border=element_line(color='black'))
	) +
	theme_classic() +
	theme(
		axis.ticks=element_blank(), axis.text=element_blank(), axis.line=element_blank(), plot.margin = unit(c(0, 0, 0, 0), "lines"), axis.title=element_blank(),
		panel.border=element_rect(color='black', fill=NA, size=1)
	) +
	coord_cartesian(
		xlim=buffered.range(grid.FPLY$long, 0),
		ylim=buffered.range(grid.FPLY$lat, 0)
	)
```


```{r, fig.width=8, fig.height=3.5, fig.cap='Climatic variation. Each panel depicts variation based on a different principle component (PC). Squares represent planning units. The color of each planning unit denotes the average PC value of pixels inside it. Planning units with more similar colors have more similar climate regimes.', echo=FALSE}
do.call(
	grid.arrange,
		append(
		llply(grep('^env\\_.*$', names(grid.DF), value=TRUE), function(x) {
			grid.FPLY$plot_title <- paste0('PC ', substr(x, nchar(x), nchar(x)))
			ggplot() +
				geom_polygon(data=countries.FPLY, aes(x=long, y=lat, group=group),
					fill='grey85', color='grey70') +
				geom_polygon(data=grid.FPLY, aes_string(x='long', y='lat', 
					group='group', fill=x), color='grey10') +
				theme_classic() +
				theme(
					axis.ticks=element_blank(), axis.text=element_blank(), axis.line=element_blank(), plot.margin = unit(c(0, 0, 0, 0), "lines"), axis.title=element_blank(),
					panel.border=element_rect(color='black', fill=NA, size=1),
					strip.background = element_rect(fill='grey20'),
					strip.text = element_text(color='white')
				) +
				coord_cartesian(
					xlim=buffered.range(grid.FPLY$long, 0),
					ylim=buffered.range(grid.FPLY$lat, 0)
				) +
				scale_fill_gradientn(name='',
					colors=brewer.pal(9, 'RdYlBu'),
					guide=guide_colorbar(ticks=element_line(color='black'), border=element_line(color='black'))
				) +
				facet_wrap(~ plot_title)
		}),
		list(ncol=2)
	)
)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=9.5, fig.height=10, fig.cap='Relative support ($BIC$) for the number of populations in each species. Each panel denotes a different species. Each line denotes a different model parametrization. Asterisks indicate the model and number of populations with the most support.'}
# format data
bic.DF <- ldply(
	seq_along(unique(spp.samples.DF$species)),
	.fun=function(i) {
		curr.MTX <- spp.Mclust.LST[[i]]$mclust$BIC
		attr(curr.MTX, 'dim') <- c(nrow(curr.MTX), ncol(curr.MTX))
		attr(curr.MTX, 'dimnames') <- list(
			seq_len(nrow(curr.MTX)),
			attr(curr.MTX, 'modelNames')
		)
		class(curr.MTX) <- 'matrix'
		curr.DF <- curr.MTX %>% as.data.frame %>% 
			mutate(G=attr(curr.MTX, 'G')) %>% 
			gather(Model,BIC,-G)
		curr.DF$BIC=curr.DF$BIC*-1
		return(
			mutate(
				curr.DF,
				Species=gsub('_', ' ', unique(spp.samples.DF$species)[i], fixed=TRUE),
				best_G=curr.DF[which.min(curr.DF$BIC),'G'][[1]],
				best_stat=min(curr.DF$BIC,na.rm=TRUE),
				asterisk_col=c('black', rep(NA_character_, length(Species)-1))
			)
		)
	}
)
# make plot
suppressWarnings({
	ggplot(data=bic.DF) +
		geom_line(aes(y=BIC, x=G, color=Model, linetype=Model)) +
		geom_point(aes(y=best_stat, x=best_G), size=4, shape=8) +
		theme_classic() +
		scale_y_reverse()+
		theme(
			strip.background = element_rect(fill='grey20'),
			strip.text = element_text(color='white', face='italic', size=20)
		) +
		xlab('Number of populations') +
		ylab('BIC') +
		scale_linetype_manual(values=rep(c('solid','dashed'),each=7)) +
		scale_color_manual(values=rep(gg_color_hue(7),2)) +
		facet_wrap(~ Species, ncol=4, scales='free_y')
})
```


```{r, echo=FALSE}
# prepare data
pop.probs.DF <- llply(
	seq_along(unique(spp.samples.DF$species)),
	function(i) {
		curr.pts <- filter(
			spp.sample.PTS@data,
			species==unique(spp.samples.DF$species)[i]
		) %>% mutate(
			Individual=seq_along(species)
		) 	
		curr.probs <- spp.Mclust.LST[[i]]$mclust$z %>%
			as.data.frame() %>%
			mutate(
				species=unique(spp.samples.DF$species)[i],
				Individual=seq_along(species)) %>%
			gather(Population,Probability,-species,-Individual) %>%
			mutate(Population=as.numeric(gsub('V', '', Population, fixed=TRUE))) %>%
			left_join(curr.pts, by=c('species','Individual')) %>%
			mutate(species=gsub('_', ' ', species, fixed=TRUE)) %>%
			arrange(species,Individual,Population)
		return(curr.probs)
	}
) %>% do.call(what=rbind)
# create legend colors
legend.CHR <- `names<-`(
	gg_color_hue(n_distinct(pop.probs.DF$Population)),
	as.character(unique(pop.probs.DF$Population))
)
# create function
plot.spp.pop.probs <- function(i) {
	# init
	prop <- 0.85
	curr.spp.DF <- filter(pop.probs.DF, species==unique(pop.probs.DF$species)[i])
	# create base map grob
	curr.GROB <- ggplot(data=curr.spp.DF) +
		geom_polygon(data=countries.FPLY, aes(x=long, y=lat, group=group),
			fill='grey85', color='grey75') +
		geom_polygon(data=grid.FPLY, aes_string(x='long', y='lat', 
			group='group'), fill='grey70', color='grey10') +
		guides(fill=guide_legend(title=''), color=guide_legend(title='')) +
		theme_classic() +
		theme(
			axis.title=element_blank(), axis.text=element_blank(),
			axis.line=element_blank(), axis.ticks=element_blank(),
			axis.ticks.length = unit(0, "cm"),
			legend.position = "none", panel.margin = unit(0, "lines"),
			plot.margin = unit(c(0, 0, 0, 0), "lines"),
			strip.background = element_rect(fill='grey20'),
			strip.text = element_text(color='white', face='italic', size=20),
			legend.text= element_text(size=20)
		) + 
		coord_cartesian(
			xlim=buffered.range(grid.FPLY$long, 0),
			ylim=buffered.range(grid.FPLY$lat, 0)
		) +
		scale_fill_manual(
			name='',
			values=legend.CHR[seq_len(n_distinct(curr.spp.DF$Population))]
		)
	# create header grob
	curr.GROBH <- ggplot() +
			geom_text(aes(x=0,y=0,label=species),
				data=curr.spp.DF[1,,drop=FALSE],
				color='white', fontface='italic', size=4) +
		theme_classic() +
		theme(
			axis.title=element_blank(), axis.text=element_blank(),
			axis.line=element_blank(), axis.ticks=element_blank(),
			axis.ticks.length = unit(0, "cm"),
			legend.position = "none", panel.margin = unit(0, "lines"),
			plot.margin = unit(c(0, 0, 0, 0), "lines"),
			panel.background=element_rect(fill='grey20')
		) +
		coord_cartesian(xlim=c(-1,1), ylim=c(-1,1))
	# create bbox object
	bbox <- c(ggplot_build(curr.GROB)$panel$ranges[[1]]$x.range,
		ggplot_build(curr.GROB)$panel$ranges[[1]]$y.range)
		names(bbox) <- c('ll.lon', 'ur.lon', 'll.lat', 'ur.lat')
	# render grob
	grid.newpage()
	pushViewport(viewport(layout=grid.layout(2,1, heights=unit(c(1-prop, prop), "npc"))))
	print(curr.GROBH, vp=viewport(layout.pos.row=1, layout.pos.col=1))
	print(curr.GROB, vp=viewport(layout.pos.row=2, layout.pos.col=1))
	# add in pies
	for (j in unique(curr.spp.DF$cell)) {
		# init
		curr.cell.DF <- filter(curr.spp.DF, cell==j) %>% 
			group_by(cell, Population) %>%
			summarize(
				grid.longitude=mean(grid.longitude), 
				grid.latitude=mean(grid.latitude),
				Probability=mean(Probability)
			) %>% data.frame()
		curr.lon <- (curr.cell.DF$grid.longitude[1]-bbox['ll.lon'])/abs(bbox['ur.lon']-bbox['ll.lon'])
		curr.lat <- ((curr.cell.DF$grid.latitude[1]-bbox['ll.lat'])/abs(bbox['ur.lat']-bbox['ll.lat']))*prop
		# create pie chart for individual
		curr.pie <- ggplot(curr.cell.DF, aes(x="", y=Probability, fill=factor(Population))) +
			geom_bar(width=0.75, color='grey20', stat='identity') +
			coord_polar(theta='y') +
			theme(
				line = element_blank(), rect = element_blank(), 
				text = element_blank(), axis.ticks.length = unit(0, "cm"),
				legend.position = "none", panel.margin = unit(0, "lines"),
				plot.margin = unit(c(0, 0, 0, 0), "lines"), complete = TRUE
			) +
			scale_fill_manual(
				name='',
				values=legend.CHR[seq_len(n_distinct(curr.spp.DF$Population))]
			)
		# render pie
		print(curr.pie, vp=viewport(x=curr.lon, y=curr.lat, width=0.075, height=0.075))
	}
}
```


```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_',' ',unique(spp.samples.DF$species)[1], fixed=TRUE),'} populations. Squares denote planning units. Pie charts denote quadrats where individuals were sampled, and colors denote the average probability that individuals in the quadrat belong to different populations on average.')}
plot.spp.pop.probs(1)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[2],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (2 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(2)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[3],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (3 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(3)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[4],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (4 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(4)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[5],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (5 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(5)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[6],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (6 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(6)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[7],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (7 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(7)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[8],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (8 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(8)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[9],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (9 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(9)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[10],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (10 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(10)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[11],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (12 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(11)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[12],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (12 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(12)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[13],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (13 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(13)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[14],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (14 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(14)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[15],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (15 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(15)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[16],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (16 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(16)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[17],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (17 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(17)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[18],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (18 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(18)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[19],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (19 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(19)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[20],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (20 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(20)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[21],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (21 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(21)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[22],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (22 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(22)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[23],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (23 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(23)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[24],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (24 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(24)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[25],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (25 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(25)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[26],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (26 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(26)
```

```{r, echo=FALSE, fig.width=3.5, fig.height=2.5, fig.cap=paste0('Distribution of \\textit{',gsub('_', ' ',unique(spp.samples.DF$species)[27],fixed=TRUE),'} populations. See Figure SX caption for conventions.')}
if (27 <= general.params.LST[[MODE]]$n.spp) plot.spp.pop.probs(27)
```

```{r, echo=FALSE}
plot.spp.nmds <- function(i) {
	## prepare data
	# get vector of adaptive and neutral column names
	adapt.col <- grep(
		paste0(unique(spp.samples.DF$species)[i], '_adaptive_d'),
		names(grid.FPLY), value=TRUE, fixed=TRUE
	)
	neutral.col <- grep(
		paste0(unique(spp.samples.DF$species)[i], '_neutral_d'),
		names(grid.FPLY), value=TRUE, fixed=TRUE
	)
	curr.FPLY <- grid.FPLY[,
		c(adapt.col, neutral.col,
		'long','lat','group'),drop=FALSE]
	curr.FPLY <- curr.FPLY[which(!is.na(curr.FPLY[[1]])),]
	curr.FPLY <- curr.FPLY %>% gather(d, value, contains('adaptive'), contains('neutral')) %>% mutate(
		d=gsub(paste0(unique(spp.samples.DF$species)[i], '_'), '', d, fixed=TRUE),
		d=gsub('_', ' ', d, fixed=TRUE)
	)
	for (j in seq_len(length(adapt.col)+length(neutral.col)))
		curr.FPLY[['d']] <- gsub(as.character(j), paste0('(', j, ')'), curr.FPLY[['d']], fixed=TRUE)
	curr.FPLY <- curr.FPLY %>% mutate(d=factor(gsub(' d(', ' (', d, fixed=TRUE)))
	# make plot
	curr.GROBS <- llply(unique(curr.FPLY$d), function(x) {
		ggplot() +
			geom_polygon(data=countries.FPLY, aes(x=long, y=lat, group=group),
				fill='grey85', color='grey70') +
			geom_polygon(data=filter(curr.FPLY, d==x), aes_string(x='long', y='lat', 
				group='group', fill='value'), color='grey10') +
			theme_classic() +
			theme(
				axis.ticks=element_blank(), axis.text=element_blank(), axis.line=element_blank(), plot.margin = unit(c(0, 0, 0, 0), "lines"), axis.title=element_blank(),
				panel.border=element_rect(color='black', fill=NA, size=1),
				strip.background = element_rect(fill='grey20'),
				strip.text = element_text(color='white', size=20)
			) +
			coord_cartesian(
				xlim=buffered.range(grid.FPLY$long, 0),
				ylim=buffered.range(grid.FPLY$lat, 0)
			) +
			scale_fill_gradientn(name='',
				colors=brewer.pal(9, 'RdYlBu'),
				guide=guide_colorbar(ticks=element_line(color='black'),
					border=element_line(color='black'), barheight=unit(7, 'cm'))
			) + facet_wrap(~d)
	})
	do.call(grid.arrange, append(curr.GROBS, list(ncol=4)))
	invisible()
}

calc.fig.height <- function(i) {
	# init
	adapt.col <- paste0(unique(spp.samples.DF$species)[i], '_adaptive_d1')
	neutral.col <- paste0(unique(spp.samples.DF$species)[i], '_neutral_d1')
	n.plots <- 0 
	# count adaptive plot
	if (adapt.col %in% names(grid.FPLY))
		n.plots <- n.plots + spp.nmds.LST[[i]][['adaptive']]$ndim
	# count neutral plot
	if (neutral.col %in% names(grid.FPLY))
		n.plots <- n.plots + spp.nmds.LST[[i]][['neutral']]$ndim
	# exports
	return(ceiling(n.plots/4) * 3.5)
}
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(1), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[1]),'}. Each panel shows a different dimension of the variation as indicated by its title. Squares represent planning units. The color of each planning unit panel corresponds to the average ordinated values associated with individuals sampled inside it. No indiviudals of this species were found inside the gray planning units.')}
if (1 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(1)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(2), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[2]),'}. See Figure S6 caption for conventions.')}
if (2 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(2)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(3), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[3]),'}. See Figure S6 caption for conventions.')}
if (3 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(3)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(4), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[4]),'}. See Figure S6 caption for conventions.')}
if (4 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(4)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(5), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[5]),'}. See Figure S6 caption for conventions.')}
if (5 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(5)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(6), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[6]),'}. See Figure S6 caption for conventions.')}
if (6 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(6)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(7), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[7]),'}. See Figure S6 caption for conventions.')}
if (7 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(7)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(8), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[8]),'}. See Figure S6 caption for conventions.')}
if (8 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(8)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(9), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[9]),'}. See Figure S6 caption for conventions.')}
if (9 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(9)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(10), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[10]),'}. See Figure S6 caption for conventions.')}
if (10 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(10)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(11), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[11]),'}. See Figure S6 caption for conventions.')}
if (11 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(11)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(12), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[12]),'}. See Figure S6 caption for conventions.')}
if (12 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(12)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(13), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[13]),'}. See Figure S6 caption for conventions.')}
if (13 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(13)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(14), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[14]),'}. See Figure S6 caption for conventions.')}
if (14 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(14)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(15), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[15]),'}. See Figure S6 caption for conventions.')}
if (15 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(15)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(16), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[16]),'}. See Figure S6 caption for conventions.')}
if (16 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(16)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(17), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[17]),'}. See Figure S6 caption for conventions.')}
if (17 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(17)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(18), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[18]),'}. See Figure S6 caption for conventions.')}
if (18 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(18)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(19), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[19]),'}. See Figure S6 caption for conventions.')}
if (19 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(19)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(20), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[20]),'}. See Figure S6 caption for conventions.')}
if (20 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(20)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(21), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[21]),'}. See Figure S6 caption for conventions.')}
if (21 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(21)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(22), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[22]),'}. See Figure S6 caption for conventions.')}
if (22 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(22)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(23), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[23]),'}. See Figure S6 caption for conventions.')}
if (23 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(23)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(24), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[24]),'}. See Figure S6 caption for conventions.')}
if (24 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(24)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(25), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[25]),'}. See Figure S6 caption for conventions.')}
if (25 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(25)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(26), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[26]),'}. See Figure S6 caption for conventions.')}
if (26 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(26)
```

```{r, echo=FALSE, fig.width=15, fig.height=calc.fig.height(27), fig.cap=paste0('Distribution of adaptive and neutral genetic variation in \\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[27]),'}. See Figure S6 caption for conventions.')}
if (27 <= general.params.LST[[MODE]]$n.spp) plot.spp.nmds(27)
```

```{r, echo=FALSE}
## make results table showing Eigen values
knitr::kable(
	pca.DF,
	digits=2,
	caption='Summary of principle components analysis (PCA) on bioclimatic variation across the study area. The first two principle components (PCs) were used for subsequent analysis.',
	align=c('l', 'c', 'c', 'c')
)
```

```{r, echo=FALSE}
knitr::kable(
	format.dataframe(
		filter(
			ldply(
				seq_along(unique(spp.samples.DF$species)), 
				function(i) {
					ldply(
						seq_along(spp.nmds.LST[[i]]),
						function(j) {
						rbind(
							data.frame(
								Species=paste0('\\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[i]),'}'),
								Loci='all',
								k=spp.Mclust.LST[[i]]$nmds$ndim,
								Stress=spp.Mclust.LST[[i]]$nmds$stress,
								Converged=spp.Mclust.LST[[i]]$nmds$converged
							),
							data.frame(
								Species=paste0('\\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[i]),'}'),
								Loci=names(spp.nmds.LST[[i]])[j],
								k=ifelse(is.null(spp.nmds.LST[[i]][[j]]), NA_integer_, spp.nmds.LST[[i]][[j]]$ndim),
								Stress=ifelse(is.null(spp.nmds.LST[[i]][[j]]), NA_real_, spp.nmds.LST[[i]][[j]]$stress),
								Converged=ifelse(is.null(spp.nmds.LST[[i]][[j]]), NA, spp.nmds.LST[[i]][[j]]$converged)
							)
						)
					})
				}
			),
			!is.na(Stress)
		),
		omit=c('Loci','Converged')
	),
	digits=2,
	caption='Summary of non-metric multi-dimensional scaling (MDS) analyses on genetic variation for each species. The analyses on all loci were used to transform the binary presence/absence polymorphism data to continuous variables to train Gaussian mixture models and ultimately identify adaptive loci. The analyses on adaptive and neutral loci were used to transform the polymorphism data to identify main gradients of this variation.',
	col.names=c('Species', 'Loci Type', 'k', 'NMDS Stress', 'Converged'),
	align=c('l', 'c', 'c', 'c', 'c')
)
```

```{r, echo=FALSE}
knitr::kable(
	format.dataframe(
		ldply(
			seq_along(unique(spp.samples.DF$species)), 
			function(i) {
				if (!is.null(spp.BayeScan.sample.loci.subset.LST[[i]])) {
					data.frame(
						Species=paste0('\\textit{',gsub('\\_', ' ', unique(spp.samples.DF$species)[i]),'}'),
						Primer=spp.BayeScan.sample.loci.subset.LST[[i]]@data@primers,
						Probability=spp.BayeScan.sample.loci.subset.LST[[i]]@results@summary[[2]],
						qval=spp.BayeScan.sample.loci.subset.LST[[i]]@results@summary[[4]],
						alpha=spp.BayeScan.sample.loci.subset.LST[[i]]@results@summary[[5]],
						fst=spp.BayeScan.sample.loci.subset.LST[[i]]@results@summary[[6]],
						Type=spp.BayeScan.sample.loci.subset.LST[[i]]@results@summary[[7]]
					)
				}
			}
		),
		omit='Type'
	),
	digits=2,
	col.names=c('Species', 'Primer', 'Probability', 'q-value', '$\\alpha$', '$F_{ST}$', 'Type'),
	align=c('l', 'c', 'c', 'c', 'c', 'c', 'c'),
	caption='Loci classifications for each species. Each row denotes a sampled loci for a given species, and the evidence for it being under selection based on outputs from the program \\texttt{Bayescan}. Note that loci in species with a single population were assumed to be neutral. Loci for these species do not appear in this table.'
)
```
