title = "rapr parameters"

[debug]

	[debug."single.species"]
	amount.target = 0.1
	amount.replicates = 10
	surrogate.target = 0.9
	surrogate.replicates = 1
	genetic.target = 0.5
	genetic.replicates = 1

	[debug."multi.species"]
	amount.target = 0.1
	amount.replicates = 1
	surrogate.target = 0.9
	surrogate.replicates = 1
	genetic.target = 0.5
	genetic.replicates = 1
	
	[debug."surrogacy.analysis"]
	surrogate.optimal.replicates = 1
	surrogate.random.replicates = 10
	surrogate.target = [0.1, 0.2, 0.3, 0.4, 0.5]


[release]

	[release."single.species"]
	amount.target = 0.1
	amount.replicates = 100
	surrogate.target = 0.9
	surrogate.replicates = 1
	genetic.target = 0.9
	genetic.replicates = 1

	[release."multi.species"]
	amount.target = 0.1
	amount.replicates = 1
	surrogate.target = 0.9
	surrogate.replicates = 1
	genetic.target = 0.9
	genetic.replicates = 1
	
	[release."surrogacy.analysis"]
	surrogate.optimal.replicates = 1
	surrogate.random.replicates = 100
	surrogate.target = [0.5,0.6,0.7,0.8,0.9]


