title = "rapr parameters"

[debug]

	[debug."single.species"]
	amount.target = 0.1
	amount.replicates = 5
	surrogate.target = 0.9
	surrogate.replicates = 1
	genetic.target = 0.9
	genetic.replicates = 1

	[debug."multi.species"]
	amount.target = 0.1
	amount.replicates = 1
	surrogate.target = 0.9
	surrogate.replicates = 1
	genetic.target = 0.9
	genetic.replicates = 1

[release]

	[release."single.species"]
	amount.target = 0.1
	amount.replicates = 1000
	surrogate.target = 0.9
	surrogate.replicates = 1
	genetic.target = 0.9
	genetic.replicates = 1

	[release."multi.species"]
	amount.target = 0.1
	amount.replicates = 1
	surrogate.target = 0.9
	surrogate.replicates = 1
	genetic.target = 0.9
	genetic.replicates = 1


