title = "rapr parameters"

[debug]
single.species.amount.replicates = 10
amount.target = 0.3
surrogate.target = 0.9
genetic.target = 0.9
pareto.surrogate.targets = [0.01, 0.505, 1]


[release]
single.species.amount.replicates = 1000
amount.target = 0.3
surrogate.target = 0.9
genetic.target = 0.9
pareto.surrogate.targets = [0.01, 0.12, 0.23, 0.34, 0.45, 0.56, 0.67, 0.78, 0.89, 1.00]

