title = "rapr parameters"

[debug]

	[debug."surrogacy.analysis"]
	optimal.replicates = 1
	random.replicates = 10
	surrogate.target = [0.75, 0.9, 0.95, 0.99]

	[debug."scenario.analysis"]
	amount.target = 0.1
	surrogate.target = 0.9
	genetic.target = 0.8
	single.species.amount.replicates = 10
	other.replicates = 1

[release]

	[release."surrogacy.analysis"]
	optimal.replicates = 1
	random.replicates = 1000
	surrogate.target = [0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]

	[release."scenario.analysis"]
	amount.target = 0.1
	surrogate.target = 0.9
	genetic.target = 0.8
	single.species.amount.replicates = 1000
	other.replicates = 1

