title = "rapr parameters"

[debug]

	[debug."surrogacy.analysis"]
	random.replicates = 10

	[debug."scenario.analysis"]
	amount.target = 0.2
	surrogate.target = 0.95
	genetic.target = 0.8
	single.species.amount.replicates = 10
	other.replicates = 1

[release]

	[release."surrogacy.analysis"]
	random.replicates = 10000

	[release."scenario.analysis"]
	amount.target = 0.2
	surrogate.target = 0.95
	genetic.target = 0.8
	single.species.amount.replicates = 1000
	other.replicates = 1

