title = "structure parameters"

[debug]
probability.threshold = 0.01
numruns = 4
burnin = 20
numreps = 30
noadmix = true
admburnin = 10
repeats = 1000
updatefreq=1
freqscorr = false

[release]
probability.threshold = 0.75
numruns = 5
burnin = 500000
numreps = 500000
noadmix = true
admburnin = 5000
repeats = 1000
updatefreq=1000
freqscorr = false
