---
fontsize: 11pt
documentclass: article
bibliography: Endnote_lib.bib
csl: reference-style.csl
output:
  rmarkdown::pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: [preamble-latex.tex, preamble-latex2.tex]
---

```{r, include=FALSE}
# set wd
knitr::opts_knit$set(root.dir=normalizePath('../..'))
```

```{r, include=FALSE}
# load .rda file
try(session::restore.session('data/final/results.rda'))

# set options
options(error=NULL)

# download basemap
data(countriesHigh)
countries.FPLY <- countriesHigh[
	countriesHigh$ADMIN %in% c(
		'Italy', 'Switzerland', 'France', 'Austria',
		'Germany', 'Slovenia', 'Croatia', 'Hungary',
		'Monaco', 'Germany', 'Slovakia', 'Czech Republic'
	)
,] %>% spFortify
grid.FPLY <- spFortify(grid.PLY)
grid.sub.FPLY <- spFortify(grid.sub.PLY)

# define ggplot2 color wheel function
gg_color_hue <- function(n) {
	hues <- seq(15, 375, length=n+1)
	hcl(h=hues, l=65, c=100)[1:n]
}

```

## Figures

<!--

```{r, echo=FALSE, fig.width=6, fig.height=1.5, fig.cap="Map of the study area. Squares denote planning units. Panel (a) depicts patterns of species riches. Planning units with a brighter color are inhabited by more species. Panel (b) shows the distribution of opportunity cost across the study area (computed as total population density). Note that a quantile-based color ramp is used in this panel."}

# calculate species richness
grid.PLY$Species_richness <- grid.PLY@data %>%
	select(5:(4+n_distinct(spp.samples.DF$species))) %>% as.matrix() %>% rowSums()
	
panel.DF <- grid.sub.FPLY %>% 
	summarize(lat=min(lat)+(diff(range(lat))*0.96),
		long=min(long)+(diff(range(long))*0.04))
	
# plot species richness
p1 <- ggplot() +
	geom_polygon(data=countries.FPLY, aes(x=long, y=lat, group=group),
		fill='grey85', color='grey70') +
	geom_polygon(data=spFortify(grid.PLY), aes(x=long, y=lat, 
		group=group, fill=Species_richness), color='grey10') +
	scale_fill_gradientn(name='Richness',
		colors=brewer.pal(9,'PuBu'),
		guide=guide_colorbar(ticks=element_line(color='black'), border=element_line(color='black'))
	) +
	theme_classic() +
	theme(
		axis.ticks=element_blank(), axis.text=element_blank(), axis.line=element_blank(), plot.margin = unit(c(0, 0, 0, 0), "lines"), axis.title=element_blank(),
		panel.border=element_rect(color='black', fill=NA, size=1)
	) +
	coord_cartesian(
		xlim=buffered.range(grid.FPLY$long, 0),
		ylim=buffered.range(grid.FPLY$lat, 0)
	) + geom_text(aes_string(x='long',y='lat'), data=panel.DF, label='(a)')
	
qn01 <- scales::rescale(quantile(grid.PLY@data$pop.density, seq(0,1,length.out=9), na.rm=TRUE))
p2 <- ggplot() +
	geom_polygon(data=countries.FPLY, aes(x=long, y=lat, group=group),
		fill='grey85', color='grey70') +
	geom_polygon(data=spFortify(grid.PLY), aes(x=long, y=lat, 
		group=group, fill=pop.density), color='grey10') +
	scale_fill_gradientn(name='Cost',
		colors=brewer.pal(9, 'PuBu'),
		values=qn01,
		guide=guide_colorbar(ticks=element_line(color='black'), border=element_line(color='black'))
	) +
	theme_classic() +
	theme(
		axis.ticks=element_blank(), axis.text=element_blank(), axis.line=element_blank(), plot.margin = unit(c(0, 0, 0, 0), "lines"), axis.title=element_blank(),
		panel.border=element_rect(color='black', fill=NA, size=1)
	) +
	coord_cartesian(
		xlim=buffered.range(grid.FPLY$long, 0),
		ylim=buffered.range(grid.FPLY$lat, 0)
	)  + geom_text(aes_string(x='long',y='lat'), data=panel.DF, label='(b)')
	
grid.arrange(p1,p2,nrow=1)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=4.5, fig.cap='The relationship between surrogates and genetic variation secured in prioritizations. Panel (a) shows the relationship between the proportion of intra-specific adaptive genetic variation and environmental variation secured in a prioritization. Similarly, panel (b) shows the relationship between the proportion of intra-specific neutral variaiton and geograpgic variation secured in a prioritization. Panels (c) and (d) show the distribution of $R^2$ values for these models.'}
# make figure
p1 <- ggplot(aes(x=surrogate.held,y=genetic.held), data=env.surrogacy.DF) +
	xlab(expression(atop('Environmental variation','secured (%)'))) + 
	ylab('Adaptive genetic\nvariation secured (%)') +
	theme_classic() + theme(axis.line.x=element_line(color='black'),
		axis.line.y=element_line(color='black')) +
	geom_text(x=0.05, y=0.95, label='(a)') +
	coord_cartesian(xlim=c(0, 1))
for (i in seq_along(env.surrogacy.LST))
	p1 <- p1 + stat_smooth(method='glm', method.args=list(family='binomial'),
		data=filter(env.surrogacy.DF, Species==unique(Species)[i]),
		fullrange=TRUE, se=FALSE, colour='black')

p2 <- ggplot(aes(x=surrogate.held,y=genetic.held), data=geo.surrogacy.DF) +
	xlab(expression(atop('Geographic variation','secured (%)'))) + 
	ylab('Neutral genetic\nvariation secured (%)') +
	theme_classic() + theme(axis.line.x=element_line(color='black'),
		axis.line.y=element_line(color='black', colour='transparent')) +
	geom_text(x=0.05, y=0.95, label='(b)') +
	coord_cartesian(xlim=c(0, 1))
for (i in seq_along(geo.surrogacy.LST))
	p2 <- p2 + stat_smooth(method='glm', method.args=list(family='binomial'),
		data=filter(geo.surrogacy.DF, Species==unique(Species)[i]),
		fullrange=TRUE, se=FALSE, colour='black')

p1.hist <- ggplot(aes(r2CU),
		data=filter(env.surrogate.spp.DF, !is.na(r2CU))) +
	geom_histogram(fill='grey10', bins=10) +
	ylab('\nFrequency') + xlab(expression(atop('Effectiveness of environmental', variables~(R^2~coefficient)))) +
	theme_classic() + theme(axis.line.x=element_line(color='black'),
		axis.line.y=element_line(color='black'),
		plot.background=element_rect(fill='transparent', colour='transparent')) +
		geom_text(x=0.05, y=0.95, label='(c)') +
		coord_cartesian(xlim=c(0, 1))

p2.hist <- ggplot(aes(r2CU),
		data=filter(geo.surrogate.spp.DF, !is.na(r2CU))) +
	geom_histogram(fill='grey10', bins=10) +
	ylab('\nFrequency') + xlab(expression(atop('Effectiveness of geographic', variables~(R^2~coefficient)))) +
	theme_classic() + theme(axis.line.x=element_line(color='black'),
		axis.line.y=element_line(color='black'), 
		plot.background=element_rect(fill='transparent')) +
		geom_text(x=0.05, y=0.95, label='(d)') +
		coord_cartesian(xlim=c(0, 1))

# render figure
grid.arrange(p1,p2,p1.hist,p2.hist,nrow=2)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=5, fig.height=5, fig.cap='Planning unit selection frequencies. The top row of panels (a, b, c) show single-species prioritizations generated assuming equal costs. The middle row of panels (d, e, f) show multi-species prioritizations generated assuming equal costs. The bottom row of panels (g, h, i) show multi-species generated using opportunity costs. The left column of panels (a, d, g) show prioritizations generated using only amount-based targets. The middle column of panels (b, e, h) show prioritizations generated using amount- and surrogate-based targets. The right column of panels (c, f, i) show prioritizations generated using amount- and genetic-based targets.'}
# prepare data for plotting
grid.sub.FPLY <- grid.sub.PLY
for (i in seq_along(single.spp.prioritisations[[1]]))
	grid.sub.FPLY@data[[paste0('Single-species (equal costs).', c('Amount', 'Surrogate', 'Genetic')[i])]] <- rowMeans(sapply(single.spp.prioritisations, function(x){colMeans(x[[i]]@results@selections)}))
for (i in seq_along(multi.spp.prioritisations))
	grid.sub.FPLY@data[[paste0('Multi-species (equal costs).', c('Amount', 'Surrogate', 'Genetic')[i])]] <- colMeans(multi.spp.prioritisations[[i]]@results@selections)
for (i in seq_along(multi.spp.prioritisations.with.cost))
	grid.sub.FPLY@data[[paste0('Multi-species (opportunity costs).', c('Amount', 'Surrogate', 'Genetic')[i])]] <- colMeans(multi.spp.prioritisations.with.cost[[i]]@results@selections)
grid.sub.FPLY <- spFortify(grid.sub.FPLY)
grid.sub.FPLY <- grid.sub.FPLY %>% gather(
		Combination,
		`Selection.Frequency`,
		`Single-species (equal costs).Amount`:`Multi-species (opportunity costs).Genetic`
	) %>% mutate(
		Context=sapply(strsplit(as.character(Combination), '.', fixed=TRUE), `[[`, 1),
		Prioritization=sapply(strsplit(as.character(Combination), '.', fixed=TRUE), `[[`, 2)
	) %>% mutate(
		Prioritization=revalue(Prioritization, c('Amount'='Amount targets', 'Surrogate'='Amount & surrogate\ntargets', 'Genetic'='Amount & genetic\ntargets')),
		Prioritization=factor(as.character(Prioritization), levels=c('Amount targets', 'Amount & surrogate\ntargets', 'Amount & genetic\ntargets')),
		Context=factor(
			gsub(' (', '\n(', Context, fixed=TRUE),
			levels=c("Single-species\n(equal costs)", "Multi-species\n(equal costs)", 
			"Multi-species\n(opportunity costs)"))
	)
panel.DF <- grid.sub.FPLY %>% select(Context, Prioritization, long, lat) %>% 
	mutate(
		lat=min(lat)+(diff(range(lat))*0.98),
		long=min(long)+(diff(range(long))*0.02)
	) %>%
	group_by(Context,Prioritization) %>% filter(c(TRUE, rep(FALSE, length(Context)-1))) %>%
	mutate(
		panel.letter=paste0('(',letters[(as.integer(Context)-1)*3 + as.integer(Prioritization)],')'),
		panel.letter=c(as.character(panel.letter[1]), rep(NA_character_, length(Context)-1))
	)
# make maps
ggplot() +
	geom_polygon(data=countries.FPLY, aes(x=long, y=lat, group=group),
		fill='grey85', color='grey70') +
	geom_polygon(data=grid.sub.FPLY, aes_string(x='long', y='lat', 
		group='group', fill='Selection.Frequency'),
		alpha=0.8, color='grey10') +
	geom_text(aes_string(x='long',y='lat', label='panel.letter'), data=panel.DF) +
	theme_classic() +
	theme(axis.ticks=element_blank(), axis.text=element_blank(),
		plot.margin=unit(c(0,0,0,0),'cm'), axis.line=element_blank(),
		strip.background = element_rect(fill='grey20'),
		strip.text = element_text(color='white'),
		legend.position='bottom', legend.key.width=unit(1.8, 'cm'),
		legend.title=element_text(vjust=-5),
		legend.margin=unit(c(0.1), 'cm'),
		axis.title=element_blank()) +
	coord_cartesian(
		xlim=buffered.range(grid.sub.FPLY$long, 0),
		ylim=buffered.range(grid.sub.FPLY$lat, 0)
	) +
	facet_grid(Context ~ Prioritization) +
	scale_fill_gradientn(name='Selection Frequency (%)',
		colors=brewer.pal(9, 'PuBu'),
		guide=guide_colorbar(title.position='bottom', title.hjust=0.5,
			ticks=element_line(color='black'), border=element_line(color='black'))
	)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=5, fig.height=5.5, fig.cap='The effectiveness of prioritizations at securing genetic variation. The top row of panels (a--b) show the performance of single-species prioritizations generated assuming equal costs among planning costs. The middle row of panels (c--d) show the performance of multi-species prioritizations generated assuming equal costs among planning units. The bottom row of panels (e--f) show the performance of multi-species prioritizations generated using opportunity costs. The left column of panels (a, c, d) and the right column of panels (b, d, f) show the proportion of adaptive and neutral genetic variation secured (respectively). Box plots show the effectiveness of prioritizations generated using amount-based targets, amount-based and surrogate-based targets, and amount-based and genetic-based targets for each species. Letters denote significant differences ($P < 0.05$).'}
# prepare data for plotting
scenario.PDF <- scenario.DF %>% group_by(Prioritisation, Context, Metric) %>% 
	mutate(
		letter.height=max(genetic.held, na.rm=TRUE)+0.1,
		Combination=paste0(Prioritisation,'.',Metric,'.',Context)) %>%
	filter(c(TRUE, rep(FALSE, length(Context)-1))) %>% 
	ungroup() %>%
	group_by(Context, Metric) %>% 
	mutate(
		panel.letter=paste0(
			'(',letters[(as.integer(Context)*2)-1 + (as.integer(Metric)-1)],')'
		),
		panel.letter=c(as.character(panel.letter[1]), rep(NA_character_, length(Context)-1))
	) %>% 
	ungroup() %>% 
	left_join(
		data.frame(
			letter=unname(scenario.G.cld$Letters),
			Combination=as.character(names(scenario.G.cld$Letters))
		) %>% mutate(Combination=as.character(Combination)),
		by='Combination'
	) %>% data.frame()

# make plot
suppressWarnings({
	ggplot(aes(x=Prioritisation,y=genetic.held),
		data=scenario.DF) +
		geom_boxplot(position=position_dodge(0.9)) +
		geom_text(aes(x=Prioritisation, y=letter.height, label=letter),
			data=scenario.PDF, position=position_dodge(0.9)) +
		geom_text(aes(x=0.6, y=1.15, label=panel.letter),
			data=scenario.PDF) +
		scale_fill_manual(name='Prioritisation',
			values=c('grey80','grey50','grey20')) +
		ylab('Genetic variation secured (%)') +
		xlab('') +
		scale_y_continuous(breaks=c(0,0.25,0.5,0.75,1), limits=c(NA, 1.2)) +
		theme_classic() +
		theme(strip.background = element_rect(fill='grey20'),
			strip.text = element_text(color='white'),
			panel.border = element_rect(color='black', fill=NA),
			axis.text.x=element_text(angle=45, hjust=1, vjust=1)) +
		geom_abline(intercept=rapr.params.LST[[MODE]]$scenario.analysis$genetic.target,
			slope=0, color='red', linetype='dashed') +
		facet_grid(Context ~ Metric)
})
```

-->


#### Supplementary info figures

```{r, echo=FALSE, message=FALSE, warnings=FALSE, fig.width=8, fig.height=8, fig.cap='The relationship between the proportion of adaptive genetic variation secured in a prioritizaiton and the proportion of environmental variation it also secures. Points represent values associated with randomly generated prioritizations. Black lines indicate average trends computed using generalised linear models with logit links. Each panel corresponds to different species.'}
# format data
curr.DF <- env.surrogacy.DF %>% filter(!is.na(genetic.held))
curr.DF2 <- env.surrogate.spp.DF %>% filter(!is.na(r2CU))
curr.DF2$R2_repr <- round(curr.DF2$r2CU,2)
curr.DF2$R2_repr <- sapply(curr.DF2$R2_repr, function(x) {as.character(as.expression(substitute(~~italic(R)^2~"="~r2, list(r2=x))))})
curr.DF2$surrogate.held <- 0.05
curr.DF2$genetic.held <- 0.95

# make plot
suppressWarnings(
	ggplot(aes(x=surrogate.held, y=genetic.held), data=curr.DF) +
		theme_classic() +
		theme(strip.background=element_rect(fill='grey20'), strip.text=element_text(color='white', face='italic', size=2.5)) +
		xlab('Environmental variation secured (%)') +
		ylab('Adaptive genetic variation secured (%)') +
		geom_point(fill='transparent') +
		stat_smooth(method='glm', method.args=list(family='binomial'), fullrange=TRUE,
			se=FALSE, color='blue') +
		geom_text(aes(label=R2_repr), data=curr.DF2, parse=TRUE, hjust=0, size=2.5, color='blue') +
		facet_wrap(~ Species, ncol=4)
)
```

```{r, echo=FALSE, message=FALSE, warnings=FALSE, fig.width=8, fig.height=8, fig.cap='The relationship between the proportion of neutral genetic variation secured in a prioritizaiton and the proportion of geographic variation it also secures. Conventions are detailed in Figure SXXX.'}
# format data
curr.DF <- geo.surrogacy.DF %>% filter(!is.na(genetic.held))
curr.DF2 <- geo.surrogate.spp.DF %>% filter(!is.na(r2CU))
curr.DF2$R2_repr <- round(curr.DF2$r2CU,2)
curr.DF2$R2_repr <- sapply(curr.DF2$R2_repr, function(x) {as.character(as.expression(substitute(~~italic(R)^2~"="~r2, list(r2=x))))})
curr.DF2$surrogate.held <- 0.05
curr.DF2$genetic.held <- 0.95

# make plot
suppressWarnings(
	ggplot(aes(x=surrogate.held, y=genetic.held), data=curr.DF) +
		theme_classic() +
		theme(strip.background=element_rect(fill='grey20'), strip.text=element_text(color='white', face='italic', size=5)) +
		xlab('Geographic variation secured (%)') +
		ylab('Neutral genetic variation secured (%)') +
		geom_point(fill='transparent') +
		stat_smooth(method='glm', method.args=list(family='binomial'), fullrange=TRUE,
			se=FALSE, color='blue') +
		geom_text(aes(label=R2_repr), data=curr.DF2, parse=TRUE, hjust=0, size=5, color='blue') +
		facet_wrap(~ Species, ncol=4)
)
```
