---
fontsize: 11pt
documentclass: article
bibliography: Endnote_lib.bib
csl: reference-style.csl
output:
  rmarkdown::pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: [preamble-latex.tex, preamble-latex2.tex]
---

```{r, include=FALSE}
# set wd
knitr::opts_knit$set(root.dir=normalizePath('../..'))
```

```{r, include=FALSE}
# load .rda file
try(session::restore.session('data/final/results.rda'))

# set options
options(error=NULL)
```
## Tables

```{r, echo=FALSE, results='asis'}
curr.file <- tempfile(fileext='.tex')
x <- correlation.model.summary.DF %>%
	select(-contains('raw')) %>%
	mutate(
		Environmental.corr.P=pvalString(Environmental.corr.P),
		Geographic.corr.P=pvalString(Geographic.corr.P), 
		blank=rep('', length(Species)),
		Species=paste0('\\textit{', gsub('\\ ', ' ', Species), '}')) %>%
	select(Species:Environmental.corr.P, Geographic.Marginal.R2:Geographic.corr.P) %>%
	latex(file=curr.file, 
		cgroup=c('', 'Environmental', 'Geographic'), n.cgroup=c(1, 4, 4), col.just=rep('c', 9),
		digits=2, rowname=NULL, first.hline.double=FALSE, booktabs=TRUE, here=TRUE,
		colheads=c('\\bfseries{Species}', '$MR^2$', '$CR^2$', '$\\chi^2$', '\\textit{P}', '$MR^2$', '$CR^2$', '$\\chi^2$', '\\textit{P}'),
		caption='Summary of maximum likelihood population-effects (MLPE) models. Briefly, for each species associated with adaptive loci, a model was fit to correlate dissimilarities among planning units where the species in terms of the adaptive genetic characteristics of individuals in them with dissimilarities in terms of the environmental conditions inside the planning units (denoted in the environmental column group). Similarly, for each species, a model was fit to correlate dissimilarities among the planning units in terms of the neutral genetic characteristics of indiviudals in them with dissimilarities in terms of the geographic position of the planning units (denoted in the geographic column group). Data shows the marginal $R^2$ ($MR^2$) and conditional $R^2$ ($CR^2$) for each model, and also the results from comparing the models to their corresponding null models. All $\\chi^2$ tests had 1 degree of freedom.'
	)
readLines(curr.file)[-1] %>% paste0(collapse='\n') %>% 
	gsub(pattern='\\cline{1-', replacement='\\cline{2-6} \\cline{8-', fixed=TRUE) %>% 
	gsub(pattern='{c}{\\textit{P}}\\tabularnewline', replacement='{c}{\\textit{P}}\\T\\B\\tabularnewline', fixed=TRUE) %>% 
	gsub(pattern='toprule', replacement='toprule[1pt]', fixed=TRUE) %>%
	gsub(pattern='bottomrule', replacement='bottomrule[1pt]', fixed=TRUE) %>%
	cat()
 ```
